spring:
  output:
    ansi:
      enabled: ALWAYS
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
  banner:
    charset: UTF-8
banner:
  charset: UTF-8
test:
  rightAnswersCountToPass: 3
  #  locale: en-US
  locale: ru-RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv